# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: github--Personal blog
email: tomwebliu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  record life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://githupTomLiu.github.io" # the base hostname & protocol for your site
twitter_username: kobe
github_username:  githupTomLiu
sina_weibo_username: DreamsTom


# Build settings
markdown: kramdown
